add processing of multiple node numbers.

diff --git a/node-down b/node-down
--- a/node-down
+++ b/node-down
@@ -1,33 +1,33 @@
 #!/bin/bash
 
-# Use this script to down one Akka cluster node. The command line parameter must be from 1 to 9.
+# Use this script to down one or more Akka cluster nodes. The command line parameters must be from 1 to 9.
 
 usage() {
-  echo "Usage: $0 node - Down cluster node, node number must be 1 through 9." ; exit 1
+  echo "Usage: $0 nodes - Down cluster nodes, node numbers must be 1 through 9." ; exit 1
 }
 
 downNode() {
   port="855"$1
+  node=$2
 
   httpStatus=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:"$port"/cluster/members)
 
   if [[ $httpStatus == 200 ]] ; then
     curl --silent -X PUT -F "operation=Down" http://localhost:"$port"/cluster/members/cluster@127.0.0.1:255"$node" | python -m json.tool
-    exit 0
+    return
   fi
 }
 
 [ $# -eq 0 ] && usage
 
-node=$1
+while [[ $# -gt 0 ]]; do
+  node=$1
+  shift
 
-if [[ $node =~ ^[1-9]$ ]] ; then
-  for i in $(seq 9) ; do downNode "$i" ; done
-else
-  echo "Cluster node number $node is invalid. The node number must be 1 through 9."
-  usage
-fi
-
-
-echo "Unable to get a response from any cluster nodes."
-exit 1
+  if [[ $node =~ ^[1-9]$ ]] ; then
+    for i in $(seq 9) ; do downNode "$i" "$node" ; done
+  else
+    echo "Cluster node number $node is invalid. The node number must be 1 through 9."
+    usage
+  fi
+done
diff --git a/node-kill b/node-kill
--- a/node-kill
+++ b/node-kill
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-# Use this script to stop one Akka cluster node. The command line parameter must be from 1 to 9.
+# Use this script to stop one or more Akka cluster nodes. The command line parameters must be from 1 to 9.
 
 usage() {
-  echo "Usage: $0 node - Stop cluster node, node number must be 1 through 9." ; exit 1
+  echo "Usage: $0 nodes - Stop cluster nodes, node numbers must be 1 through 9." ; exit 1
 }
 
 stopNode() {
@@ -15,13 +15,17 @@ stopNode() {
 
 [ $# -eq 0 ] && usage
 
-node=$1
 scriptPath=$(dirname "$0")
 jarFilename=$(find "$scriptPath"/target -name "*allinone.jar*")
 
-if [[ $node =~ ^[1-9]$ ]] ; then
-  stopNode "$node"
-else
-  echo "Cluster node number $node is invalid. The node number must be 1 through 9."
-  usage
-fi
+while [[ $# -gt 0 ]]; do
+  node=$1
+  shift
+
+  if [[ $node =~ ^[1-9]$ ]] ; then
+    stopNode "$node"
+  else
+    echo "Cluster node number $node is invalid. The node number must be 1 through 9."
+    usage
+  fi
+done
